name: Upload RDF to S3 and Generate CSVs

on:
  push:
    paths:
      - 'spear/*.ttl'

jobs:
  upload-rdf-to-s3:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: ${{ secrets.AWS_TRIPLESTORE_BUCKET_NAME }}
      NAMED_GRAPH: https://spear-prosop.org
      SUBGRAPH: https://spear-prosop.org#data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_SPEAR_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-data
          role-duration-seconds: 28800

      - name: Generate CSVs and Upload TTL Files
        run: |
          mkdir -p build

          echo "sd:name,sd:graph,filename" > build/graph_file_associations.csv
          echo "sd:name,label,description,license,load_status" > build/named_graphs.csv

          echo "$NAMED_GRAPH,,Syriac Persons Graph,," >> build/named_graphs.csv

          find spear -name '*.ttl' | while read file; do
            filename=$(basename "$file")
            cp "$file" build/"$filename"
            echo "$NAMED_GRAPH,$SUBGRAPH,$filename" >> build/graph_file_associations.csv
          done

          aws s3 sync build/ s3://$BUCKET_NAME/spear 
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_LINKED_DATA_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}      

      - name: Trigger Lambda by uploading trigger.txt
        run: |
          echo "load" > trigger.txt
          aws s3 cp trigger.txt s3://$BUCKET_NAME/trigger.txt 

        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_LINKED_DATA_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
